CREATE INDEX IF NOT EXISTS SCHOOL_ADMINS_SCHOOL_ID_IDX ON SCHOOL_ADMINS (SCHOOL_ID);
CREATE INDEX IF NOT EXISTS SCHOOL_TEACHERS_SCHOOL_ID_IDX ON SCHOOL_TEACHERS (SCHOOL_ID);
CREATE INDEX IF NOT EXISTS ROOM_LESSONS_ROOM_ID_IDX ON ROOM_LESSONS (ROOM_ID);
CREATE INDEX IF NOT EXISTS TEACHER_ASSIGNED_LESSONS_ROOM_LESSON_ID_IDX ON TEACHER_ASSIGNED_LESSONS (ROOM_LESSON_ID);
CREATE INDEX IF NOT EXISTS DANCER_ASSIGNED_LESSONS_ROOM_LESSON_ID_IDX ON DANCER_ASSIGNED_LESSONS (ROOM_LESSON_ID);
CREATE INDEX IF NOT EXISTS DANCER_SCHOOLS_SCHOOL_ID_IDX ON DANCER_SCHOOLS (SCHOOL_ID);
