CREATE TABLE IF NOT EXISTS ASSIGNED_LESSON_DANCER_PAIRS (
    ID             NUMERIC(15, 0) NOT NULL,
    ROOM_LESSON_ID NUMERIC(14, 0) NOT NULL,
    EMAIL_1        VARCHAR(250)   NOT NULL,
    EMAIL_2        VARCHAR(250)   NOT NULL,
    STATUS         VARCHAR(25)    NOT NULL,
    CONSTRAINT ASSIGNED_LESSON_DANCER_PAIRS_PK PRIMARY KEY (ID),
    CONSTRAINT ASSIGNED_LESSON_DANCER_PAIRS_LESSON_ID_FK FOREIGN KEY (ROOM_LESSON_ID) REFERENCES ROOM_LESSONS (ID)
);
CREATE SEQUENCE IF NOT EXISTS ASSIGNED_LESSON_DANCER_PAIRS_S
    START 1
    CACHE 1;
CREATE INDEX IF NOT EXISTS ASSIGNED_LESSON_DANCER_PAIRS_ROOM_LESSON_ID_IDX ON ASSIGNED_LESSON_DANCER_PAIRS (ROOM_LESSON_ID);
