CREATE TABLE IF NOT EXISTS LESSON_TYPES (
    ID          NUMERIC(14, 0) NOT NULL,
    SCHOOL_ID   NUMERIC(7, 0)  NOT NULL,
    NAME        VARCHAR(200)   NOT NULL,
    DESCRIPTION VARCHAR(3000)  NOT NULL,
    CONSTRAINT LESSON_TYPES_PK PRIMARY KEY (ID),
    CONSTRAINT LESSON_TYPES_SCHOOL_ID_FK FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOLS (ID)
);
CREATE SEQUENCE IF NOT EXISTS LESSON_TYPES_S
    START 1
    CACHE 1;

CREATE INDEX IF NOT EXISTS LESSON_TYPES_SCHOOL_ID_IDX ON LESSON_TYPES (SCHOOL_ID);
