CREATE TABLE IF NOT EXISTS USERS (
    ID          NUMERIC(14, 0) NOT NULL,
    STATUS VARCHAR(31) NOT NULL,
    EMAIL   VARCHAR(250),
    FIRST_NAME   VARCHAR(250),
    LAST_NAME   VARCHAR(250),
    PHONE   VARCHAR(9),
    PASSWORD_HASH VARCHAR(512),
    CONSTRAINT USERS_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE IF NOT EXISTS USERS_S
    START 1
    CACHE 1;

CREATE INDEX IF NOT EXISTS USERS_EMAIL_IDX ON USERS (EMAIL);
