CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID NUMERIC(14, 0) NOT NULL,
    ROLE_CODE   VARCHAR(13) NOT NULL,
    CONSTRAINT USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_CODE),
    constraint USER_ROLES_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
