CREATE TABLE IF NOT EXISTS SIGN_UP_TEACHER (
    EMAIL VARCHAR(256) NOT NULL,
    LAT NUMERIC(8, 6) NOT NULL,
    LNG NUMERIC(9, 6) NOT NULL,
    DISTANCE NUMERIC(4) NOT NULL,
    CONSTRAINT SIGN_UP_TEACHER_PK PRIMARY KEY (EMAIL)
);

CREATE TABLE IF NOT EXISTS SIGN_UP_TEACHER_STYLES (
    EMAIL VARCHAR(256) NOT NULL,
    STYLE   VARCHAR(50) NOT NULL,
    CONSTRAINT SIGN_UP_TEACHER_STYLES_PK PRIMARY KEY (EMAIL, STYLE),
    constraint SIGN_UP_TEACHER_STYLES_PK_EMAIL_FK FOREIGN KEY (EMAIL) REFERENCES SIGN_UP_TEACHER(EMAIL)
);
CREATE INDEX IF NOT EXISTS SIGN_UP_TEACHER_STYLES_EMAIL_IDX ON SIGN_UP_TEACHER_STYLES (EMAIL) ;
