CREATE TABLE IF NOT EXISTS SIGN_UP_DANCE_FLOOR_OWNER (
    EMAIL VARCHAR(256) NOT NULL,
    LAT NUMERIC(8, 6) NOT NULL,
    LNG NUMERIC(9, 6) NOT NULL,
    CONSTRAINT SIGN_UP_DANCE_FLOOR_OWNER_PK PRIMARY KEY (EMAIL)
);
