CREATE TABLE IF NOT EXISTS SCHOOL_ROOMS (
    ID      NUMERIC(8, 0) NOT NULL,
    SCHOOL_ID      NUMERIC(7, 0) NOT NULL,
    NAME    VARCHAR(250)  NOT NULL,
    CONSTRAINT SCHOOL_ROOMS_PK PRIMARY KEY (ID),
    CONSTRAINT SCHOOL_ROOMS_SCHOOL_ID_FK FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOLS(ID)
);
CREATE SEQUENCE IF NOT EXISTS SCHOOL_ROOMS_S
    START 1
    CACHE 1;
