CREATE TABLE IF NOT EXISTS ROOM_LESSONS (
    ID          NUMERIC(14, 0)           NOT NULL,
    ROOM_ID     NUMERIC(7, 0)            NOT NULL,
    START_TIME  TIMESTAMP WITH TIME ZONE NOT NULL,
    END_TIME    TIMESTAMP WITH TIME ZONE NOT NULL,
    DESCRIPTION VARCHAR(500)             NOT NULL,
    COLOR       VARCHAR(50)              NOT NULL,
    TEXT_COLOR  VARCHAR(50)              NOT NULL,
    PUBLISHED   BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT ROOM_LESSONS_PK PRIMARY KEY (ID),
    CONSTRAINT ROOM_LESSONS_ROOM_ID_FK FOREIGN KEY (ROOM_ID) REFERENCES SCHOOL_ROOMS (ID)
);
CREATE SEQUENCE IF NOT EXISTS ROOM_LESSONS_S
    START 1
    CACHE 1;
