CREATE TABLE IF NOT EXISTS TEACHER_ASSIGNED_LESSONS (
    ID      NUMERIC(15, 0) NOT NULL,
    ROOM_LESSON_ID NUMERIC(14, 0)  NOT NULL,
    EMAIL   VARCHAR(250)   NOT NULL,
    CONSTRAINT TEACHER_ASSIGNED_LESSONS_PK PRIMARY KEY (ID),
    CONSTRAINT TEACHER_ASSIGNED_LESSONS_ROOM_LESSON_ID_FK FOREIGN KEY (ROOM_LESSON_ID) REFERENCES ROOM_LESSONS (ID)
);
CREATE SEQUENCE IF NOT EXISTS TEACHER_ASSIGNED_LESSONS_S
    START 1
    CACHE 1;
