CREATE TABLE IF NOT EXISTS DANCER_SCHOOLS (
    SCHOOL_ID      NUMERIC(7, 0) NOT NULL,
    EMAIL    VARCHAR(250)  NOT NULL,
    CONSTRAINT DANCER_SCHOOLS_PK PRIMARY KEY (SCHOOL_ID, EMAIL),
    CONSTRAINT DANCER_SCHOOLS_SCHOOL_ID_FK FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOLS(ID)
);
