spring:
    application.name: 'JoyFromDanceWebsite'
    banner.location: classpath:/JoyFromDanceWebsiteBanner.txt
    mvc.view:
        prefix: '/pages/'
        suffix: '.jsp'

management:
    server.port: 8981
    endpoints.web.exposure.include: health,info,env,metrics,prometheus,threaddump,heapdump,loggers,readiness
    metrics.export.prometheus.enabled: true
    endpoint:
        info:
            enabled: true
        env:
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled: true
        flyway:
            enabled: false
        threaddump:
            enabled: true
        heapdump:
            enabled: true
        loggers:
            enabled: true

debug: false

joy.from.dance:
    rest.url: https://rest.joyfrom.dance
joy.from.dance.website:
    security.ssl.redirect.encforce: false
    google.api.key: ''
    gtag: '...cut...'
